image: ubuntu:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get -qq update
  - apt-get -qq -y install lsb-release
  - lsb_release -a
  - apt-get -qq -y install
    clang-6.0
    g++-8
    cmake
    build-essential
    libc++-dev
    libogg-dev
    libvorbis-dev
    libopenal-dev
    libboost-all-dev
    libsdl2-dev
    libsdl2-image-dev
    libsdl2-mixer-dev
    libjsoncpp-dev
    libpng-dev
    libglew-dev
    software-properties-common

build:flatpak:
  stage: build
  script:
    - add-apt-repository -y ppa:alexlarsson/flatpak
    - apt-get -qq update
    - apt-get -qq -y install flatpak flatpak-builder
    - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - flatpak install -y flathub org.freedesktop.Platform org.freedesktop.Sdk
    - flatpak-builder --repo=build-flatpak-repo/ build-flatpak/ org.supertux.SuperTux.json
    - flatpak build-bundle build-flatpak-repo/ supertux.flatpak org.supertux.SuperTux
  artifacts:
    paths:
      - supertux.flatpak
      - build-flatpak-repo

# EOF #
